server:
  port: 9001

spring:
  application:
    name: auth-service

  datasource:
    url: ${DB_HOST:jdbc:postgresql://localhost:5432/ms_auth_service_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:root}

  jpa:
    show-sql: false
    hibernate.ddl-auto: create
    properties.hibernate.enable_lazy_load_no_trans: true
    properties.hibernate.format_sql: true
    properties.hibernate.generate_statistics: false
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    properties.hibernate.jdbc.batch_size: 20
    properties.hibernate.order_inserts: true
    properties.hibernate.order_updates: true
    properties.hibernate.jdbc.batch_versioned_data: true
    properties.hibernate.temp.use_jdbc_metadata_defaults: false

### Zipkin
  zipkin:
    enabled: true
    sender:
      type: web
    base-url: ${ZIPKIN_DEFAULT_URL:http://localhost:9411}

eureka:
  instance:
    instance-id: ${spring.application.name}-${random.uuid}
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVICE_URL:http://localhost:8761/eureka/}

client: # TODO: add to config server
  client-secret-ui: secret
  client-secret-server: secret
  signing-key: 123
  access-token-expire: 9999999
  refresh-token-expire: 9999999

springdoc:
  swagger-ui:
    path: /api/auth/api-docs

