server:
  port: 9000
spring:
  application:
    name: gateway-service

### Spring Cloud
  cloud:
    discovery:
      enabled: true

### Gateway
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/api/account/**
          filters:
            - RewritePath=/account-service/(?<path>.*), /$\{path}

        - id: balance-service
          uri: lb://balance-service
          predicates:
            - Path=/api/balance/**
          filters:
            - RewritePath=/balance-service/(?<path>.*), /$\{path}

        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
          filters:
            - RewritePath=/balance-service/(?<path>.*), /$\{path}

        - id: profile-service
          uri: lb://profile-service
          predicates:
            - Path=/api/profile/**
          filters:
            - RewritePath=/profile-service/(?<path>.*), /$\{path}

### Zipkin
  zipkin:
    enabled: true
    sender:
      type: web
    base-url: ${ZIPKIN_DEFAULT_URL:http://localhost:9411}

### Eureka
eureka:
  instance:
    instance-id: ${spring.application.name}-${random.uuid}
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVICE_URL:http://localhost:8761/eureka/}